#!/bin/bash

mkdir -p dpl_s3
if [ "$TRAVIS_OS_NAME" == "osx" ]; then
  .installer/darwin/build;
fi
if [ "$TRAVIS_OS_NAME" == "osx" ]; then
  mkdir -p dpl_s3/latest;
  cp .installer/darwin/cache/GatebluService* dpl_s3/latest;
fi
if [ "$TRAVIS_OS_NAME" == "osx" ]; then
  mkdir -p "dpl_s3/${TRAVIS_TAG}";
  cp .installer/darwin/cache/GatebluService* "dpl_s3/${TRAVIS_TAG}";
fi
